import ShoppingCart from "@/components/cart/ShoppingCart";
import Navbar from "@/components/header/navbar";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { jwtDecode } from "jwt-decode";
import { useTranslation } from "next-i18next";
import Head from "next/head";
import { User } from "@/types/types";
import { getUser } from "@/services/UserService";

interface DecodedToken {
  userId: string;
}

const Cart: React.FC = () => {
  const { t } = useTranslation();

  const [user, setUser] = useState<User>();
  useEffect(() => {
    const token =
      typeof window !== "undefined" ? localStorage.getItem("token") : null;
    if (!token) {
      return;
    }
    const decodedToken = jwtDecode<DecodedToken>(token);
    const fetchUser = async () => {
      const user = await getUser(String(decodedToken.userId));
      setUser(user);
    };
    fetchUser();
  }, []);

  return (
    <>
      <Head>
        <title>{t("cart.title")}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo-512-white.svg" />
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        />
      </Head>
      <Navbar type="cart" user={user} />
      <main className="overscroll-y-contain">
        {user && user.id ? (
          <ShoppingCart userId={user.id} />
        ) : (
          <div>{t("cart.nouserid")}</div>
        )}
      </main>
    </>
  );
};
export const getServerSideProps = async (context: { locale: any }) => {
  const { locale } = context;
  return {
    props: {
      ...(await serverSideTranslations(locale ?? "en", [`common`])),
    },
  };
};
export default Cart;
