name: Build and deploy Node.js project to Azure Function App - CNE-Group8-FunctionApp

on:
  push:
    branches:
      - main
    paths:
      - "back-end/**"
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: "CNE-Group8-FunctionApp"
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "back-end"
  NODE_VERSION: "20.x"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install, Build, and Test
        working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip function app for deployment
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          zip -r ../release.zip ./*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip -d package

      - name: Show contents of deployment package (debug)
        run: ls -R package

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          slot-name: "Production"
          package: package
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CCDBD468876E455E834D3EAE8B886EBA }}
