import Head from "next/head";
import LoginForm from "@/components/login/loginForm";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useTranslation } from "next-i18next";
import LoginTable from "@/components/loginTable/loginTable";
import AddProduct from "@/components/addProduct/addProduct";
import Navbar from "@/components/header/navbar";

const Profile: React.FC = () => {
  const { t } = useTranslation();

  return (
    <>
      <Head>
        <title>{t("login.login")}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo-512-white.svg" />
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        />
      </Head>
      <Navbar />
      {/* <main className="min-h-screen flex flex-col justify-center gap-5 overscroll-y-contain">
        <AddProduct />
      </main> */}
      <main>
        <p className="text-center font-bold text-2xl">We are currently working on implementing this feature.</p>
        <p className="text-center font-bold text-2xl">Please come back later</p>
      </main>
    </>
  );
};

export const getServerSideProps = async (context: { locale: any }) => {
  const { locale } = context;
  return {
    props: {
      ...(await serverSideTranslations(locale ?? "en", [`common`])),
    },
  };
};

export default Profile;
